### PR TITLE
Add message card and add style to buttons and input

### PR DESCRIPTION
**Pull request by jgsheppa**
I add the message cards, but I also thought that the input could have a more visible border, so I made it a bit darker. Additionally, I added some border-radius styles to the buttons. 

The room number in the top corner looked a bit lonely, so I added 'Room' before it, so that it was completely clear where the chat is taking place. I hope these changes are okay with you.

All the best,

James

### CODE REVIEW

**Comment by shrinish123** [comment]
Oh Sorry, for responding you late , thanks for contributing , but now your pull request is showing some conflicts , if you can solve them and create the pull request then it will be great

**Comment by shrinish123** [comment]
Oh Sorry, for responding you late, thanks for contributing , but now your pull request is showing some conflicts , if you can solve them and create the pull request then it will be great

**Comment by jgsheppa** [comment]
Hey @shrinish123 looks like everything is resolved now!

**Comment by shrinish123** [comment]
Oh great, thanks for your contribution,

**Pull request merged**
