### PR TITLE
kitarp29 added registration system and backend

### PR DESCRIPTION
**Pull request by kitarp29**
issue #5 
Hey, @shrinish123 I implemented an email register and login system in the repo.
I made the system in Mongo DB, though the DB, for now, is an offline one.
You can create a Mongo DB with your Id and easily connect it with the app.
For testing purposes, you can clone the repo and start MongoDB offline. [Here](https://docs.mongodb.com/manual/tutorial/install-mongodb-on-windows/) .
If you want to make a MongoDB online and connect it [Here](https://dev.to/dalalrohit/how-to-connect-to-mongodb-atlas-using-node-js-k9i), Create the cluster and replace this ```mongodb://localhost:27017/userDB``` with your URL.
The UI/UX is not that great but still fulfills the purpose. 
Things I implemented-
- Installed ```Mongoose``` and created the userschema for the DB
- Added ```ejs``` as it is an easier and faster way to transfer variables among pages via server.
- Made three pages home, register, and log in.

More things to work on -
- Better UI/UX that some Frontend can handle (add CSS file in the ```/public``` folder)
- The user Passwords are not encrypted in the DB right now. If needed I can work on it as well
- OAuth by various modes can be applied, I can work on it but that's an issue of privates keys 

ScreenShots-
image
image
image

### CODE REVIEW

**Comment by shrinish123** [comment]
Great, your work is indeed awesome, thanks a lot for your contribution, I am merging your PR.

**Comment by shrinish123** [comment]
I tested your work and  I see there is no validation like the same user can register more than 1 time and also if the user has not registered and tries to login it does not show errors neither it consoles it to the log. The screen just keeps loading and most important after registering and joining the room the chat app doesn't work, mostly because you out the socket code in the app.get('/index.js)  which is the  wrong place to put it up .

So for now I am reverting back your pull request and hoping that you improve all the errors

**Comment by kitarp29** [comment]
Hey @shrinish123 
I am pretty sure that the user cannot register with the same email id multiple times.
The mongoose driver takes care of it. Yes , I might have to add console mssgs or some error mssg pop up for user.
I will include that.
Yes the index.js can be accessed even without registering, I will take of it in the next PR.
I have one Question though where to put the socket code ? if not in the index.js
As soon as you clear out my this query I will work on the rest of the stuff and generate a new PR

**Comment by shrinish123** [comment]
database error

This is an image from my database login which clearly shows that multiple registrations form the same user are possible,
Also, there is some problem with the login part. like it's not that you have not added console messages to log the error but even after you have the error message o log it does not do so and the screen just keeps on loading.

And about where to put the socket code, I will research this and get back to you. All the Best

**Comment by kitarp29** [comment]
Ok, I can take care of that. In the ```userschema```  I will set email as *unique*.
 Please let me know about the socket code placement though.
 I will work on these issues.
 Since I am focusing on this project can you take care of my id evaluations n Kwoc?
 @shrinish123

**Comment by shrinish123** [comment]
I will tell you about the socket code by tonight
And about the comments on your project, bingo even I use the same comments for my testing :) 
I didn't understand by taking care of id evaluations of GSoC and what  you mean to say, but if you are worried about  the mid evals, you need to only have 1 pull request, so for that just make a login page and register page nonfunctional only the frontend( HTML CSS)  and make a pull request and I will merge it so that for the next part you can work on the backend peacefully but please take time and do it with proper care

**Comment by kitarp29** [comment]
Hey, @shrinish123 Sorry I got occupied with college exams.
What about the Socket code??
Where to keep them?

**Pull request merged**
